add guard usage for hanami
hanami/snippets pull request #11
Opened 2019-02-27 12:22 UTC by whysthatso

this article has very early beginner level developers in mind.

it contains the part of toolchain usage about testing that glues together the bullet points one can usually find in generic howtos.

open for edits/expansion.

2019-02-28 10:53 UTC, davydovanton approved these changes
:+1:

2019-03-01 08:17 UTC, kaikuchn commented
Hey Andreas,

thank you for following up on this!
Have you taken a look at the readme of this project? It explains how to generate a beautiful cover image for your post. You then need to rename that cover image to the same name as the markdown file (except for the suffix of course).

Could you add this image and display it in the PR-description?
I'll hopefully get around to read through the post later today and give your more feedback on it.

2019-03-03 10:04 UTC, kaikuchn requested changes
I'd suggest to fixate on RSpec for this snippet. It would read much easier and straight forward that way. We also can expect that people can transfer this knowledge and substitute the required parts if they want to use Minitest.
But you should then also put RSpec into the title.

2019-03-03 10:04 UTC, kaikuchn commented on content/posts/use-guard-with-rspec.md
> +Binding it to your Hanami project, it makes a lot of sense to add it to your Gemfile under the test group. Do not require it here, as it is not necessary to load it when your app starts up. Putting i
I find the wording of this paragraph confusing. Are you explaining what not to do? I'd just leave that out as it may just confuse people.

2019-03-18 17:35 UTC, whysthatso commented on content/posts/use-guard-with-rspec.md
> +Binding it to your Hanami project, it makes a lot of sense to add it to your Gemfile under the test group. Do not require it here, as it is not necessary to load it when your app starts up. Putting i
i was trying to explain something i did not actually put here, that is true:

```
group :development do
  gem 'guard', require: false
  gem 'guard-rspec', require: false
end
```

the paragraph is supposed to provide a colloquial explanation of a) the `development` group and b) the parameter `require: false`

indeed, the current wording sucks

2021-06-17 09:13 UTC, closed without merging