Add snippet explaining repository bulk updates
hanami/snippets pull request #3
Opened 2018-10-30 15:59 UTC by kaikuchn

User @choonggg in the hanamig gitter chat was struggling to implement a dynamic
bulk update using hanami-model.
(See https://gitter.im/hanami/chat?at=5bc4ac35c08b8b30671b2696)

This explains how to achieve a simple bulk update for publishing books, how to
generalize this into an `update_all` method and briefly discusses the merits of
not exposing such a general `update_all` method.

2018-10-31 07:48 UTC, jodosha requested changes
@kaikuchn This is a really good one. 👍 

There is one thing to change: the file name of the image.
We have a convention, both the `.md` and the `.png` file must have the same file name. In this specific case they must be named:

  * `content/posts/hanami-repository-bulk-update.md`
  * `static/covers/hanami-repository-bulk-update.png`

Did you generate the cover with the `bin/export` script?

2018-10-31 07:48 UTC, jodosha commented on content/posts/hanami-repository-bulk-update.md
> +draft: true
@kaikuchn Please don't forget to set this to `false`. We should probably remove it from the code generator.

2018-10-31 17:12 UTC, kaikuchn commented
I did generate the file with `bin/export`. But at the end, after displaying the image in my terminal it outputs

```sh
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
```

Which probably means that a `mv` command failed. Adding `set -x` to the script shows this:

```sh
+ IFS='
	'
+ snippet=hanami-repository-bulk-update
+ post=content/posts/hanami-repository-bulk-update.md
+ code=tmp/hanami-repository-bulk-update.rb
+ dir=static/covers
+ mkdir -p static/covers
+ mkdir -p tmp
+ fences=($(grep -n "\`\`\`" $post | cut -d":" -f 1))
++ grep -n '```' content/posts/hanami-repository-bulk-update.md
++ cut -d: -f 1
+ starting=19
+ ending=28
+ sed -n 19,28p content/posts/hanami-repository-bulk-update.md
+ carbon-now tmp/hanami-repository-bulk-update.rb -l static/covers -t hanami-snippets
 ✔ Processing tmp/hanami-repository-bulk-update.rb
 ✔ Preparing connection
 ↓ Opening in browser [skipped]
 ✔ Fetching beautiful image
 ↓ Copying image to clipboard [skipped]

  Done!

  The file can be found here: static/covers/hanami-snippets.png 😌

  iTerm2 should display the image below. 😊

++ find static -path 'static/covers/hanami-repository-bulk-update*'
+ generated=
+ mv static/covers/hanami-repository-bulk-update.png
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
```

So `generated` is empty because the script is looking for `static/covers/hanami-repository-bulk-update*` while the file that was generated is `static/covers/hanami-snippets.png`?

I'll manually rename the file for now.

2018-11-08 14:24 UTC, jodosha approved these changes

2018-11-08 15:44 UTC, merged